#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BMIaplikacja.Resource", IsApplication=true)]

namespace BMIaplikacja
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040012
			public const int buttonsprawdz = 2130968594;
			
			// aapt resource value: 0x7f040002
			public const int podanaWaga = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int podanyWiek = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int podanyWzrost = 2130968580;
			
			// aapt resource value: 0x7f040008
			public const int radioGroup1 = 2130968584;
			
			// aapt resource value: 0x7f04000c
			public const int radioGroup2 = 2130968588;
			
			// aapt resource value: 0x7f040009
			public const int radioKobieta = 2130968585;
			
			// aapt resource value: 0x7f04000d
			public const int radioaktyw1 = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int radioaktyw2 = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int radioaktyw3 = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int radioaktyw4 = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int radioaktyw5 = 2130968593;
			
			// aapt resource value: 0x7f04000a
			public const int radiomezczyna = 2130968586;
			
			// aapt resource value: 0x7f040000
			public const int scrollView1 = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int textView1 = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int textView2 = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int textView3 = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int textView4 = 2130968587;
			
			// aapt resource value: 0x7f040005
			public const int textView5 = 2130968581;
			
			// aapt resource value: 0x7f040013
			public const int wynik = 2130968595;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Wynik = 2130837505;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
